server.port=8080
spring.application.name=ms-digitalfix-bff

# Configuracion Azure AD
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/cc0041c5-4918-4ed1-9a20-23dc386471d4/v2.0
spring.security.oauth2.resourceserver.jwt.audiences=898e9076-6eb3-4901-a900-1017f8a7a2f6
# Modo chismoso para ver por que Azure rechaza el token
logging.level.org.springframework.security=DEBUG
