version: '3.8'

networks:
  digitalfix-net:
    driver: bridge

services:
  # 1. Base de Datos Oracle XE
  oracle-db:
    image: gvenzl/oracle-xe:slim
    container_name: oracle-digitalfix
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"
    networks:
      - digitalfix-net

  # 2. Microservicio Catálogo
  ms-catalog:
    build: ./Digitalfix-Catalog
    container_name: ms-catalog
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:XE
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
    depends_on:
      - oracle-db
    networks:
      - digitalfix-net

  # 3. Microservicio Workorders
  ms-workorders:
    build: ./Digitalfix-workorders
    container_name: ms-workorders
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521:XE
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=oracle
    depends_on:
      - oracle-db
    networks:
      - digitalfix-net

  # 4. Microservicio BFF
  ms-bff:
    build: ./Digitalfix-bff
    container_name: ms-bff
    ports:
      - "8080:8080"
    networks:
      - digitalfix-net

  # 5. Frontend React (Vite + Nginx)
  frontend:
    build:
      dockerfile: DockerFile
      context: ./Digitalfix_Frontend
      args:
        VITE_API_BASE_URL: https://digitalfix-api.duckdns.org
        VITE_AZURE_CLIENT_ID: 898e9076-6eb3-4901-a900-1017f8a7a2f6
        VITE_AZURE_TENANT_ID: cc0041c5-4918-4ed1-9a20-23dc386471d4
        VITE_AZURE_REDIRECT_URI: https://digitalfix-app.duckdns.org
        VITE_AZURE_API_SCOPE: api://898e9076-6eb3-4901-a900-1017f8a7a2f6/access_as_user

    container_name: frontend-digitalfix
    ports:
      - "5173:80"
    depends_on:
      - ms-bff
    networks:
      - digitalfix-net