# Puerto del microservicio de Catálogo (usamos el 8081 para no chocar con el BFF en el 8080)
server.port=8081
spring.application.name=ms-digitalfix-catalog

# ---------------------------------------------------------
# CONEXIÓN A LA BASE DE DATOS ORACLE EN DOCKER
# ---------------------------------------------------------
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username=SYSTEM
spring.datasource.password=oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ---------------------------------------------------------
# CONFIGURACIÓN DE HIBERNATE / JPA
# ---------------------------------------------------------
# 'update' creará las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect